// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHDFm3KoTOMMzEneuqjFESosh-2xtnqSI',
    appId: '1:920158679789:web:faea1e92390730b24652e4',
    messagingSenderId: '920158679789',
    projectId: 'cars-project-45cd3',
    authDomain: 'cars-project-45cd3.firebaseapp.com',
    storageBucket: 'cars-project-45cd3.appspot.com',
    measurementId: 'G-1FEF1SDJ5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlxOFGRrrIUSmq4y6_S5Ruy1aQTfMAhow',
    appId: '1:920158679789:android:c5c9a7754fd1efe14652e4',
    messagingSenderId: '920158679789',
    projectId: 'cars-project-45cd3',
    storageBucket: 'cars-project-45cd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJxmVk-ec5UTUWq1X3oYt05cqrX8v9JXE',
    appId: '1:920158679789:ios:82fc562c5a401db54652e4',
    messagingSenderId: '920158679789',
    projectId: 'cars-project-45cd3',
    storageBucket: 'cars-project-45cd3.appspot.com',
    iosBundleId: 'com.example.gam3aCarsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJxmVk-ec5UTUWq1X3oYt05cqrX8v9JXE',
    appId: '1:920158679789:ios:82fc562c5a401db54652e4',
    messagingSenderId: '920158679789',
    projectId: 'cars-project-45cd3',
    storageBucket: 'cars-project-45cd3.appspot.com',
    iosBundleId: 'com.example.gam3aCarsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHDFm3KoTOMMzEneuqjFESosh-2xtnqSI',
    appId: '1:920158679789:web:b02553f871ef9e414652e4',
    messagingSenderId: '920158679789',
    projectId: 'cars-project-45cd3',
    authDomain: 'cars-project-45cd3.firebaseapp.com',
    storageBucket: 'cars-project-45cd3.appspot.com',
    measurementId: 'G-XP1SJ8C7W6',
  );
}
